; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

upload_speed = 921600

lib_deps = 
    smougenot/TM1637@0.0.0-alpha+sha.9486982048
    esp32async/ESPAsyncWebServer@^3.10.3
    gyverlibs/GTimer@^1.1.1
    miguelbalboa/MFRC522@^1.4.12
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    jgromes/RadioLib@^7.7.1

extra_scripts = pre:scripts/convert_web_files.py

[env:debug]
extends = env:esp32-s3-devkitc-1
build_type = debug
build_flags = 
    ${env:esp32-s3-devkitc-1.build_flags}
    -DDEBUG

[env:release]
extends = env:esp32-s3-devkitc-1
build_type = release
build_flags = 
    ${env:esp32-s3-devkitc-1.build_flags}
    -DNDEBUG

[platformio]
description = Life Button for airsoft