; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 160000000
board_build.f_flash = 80000000
board_build.board_build.flash_mode = dio
build_flags = 	
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
upload_speed = 921600
monitor_dtr = 0
monitor_rts = 0
lib_deps = 
	smougenot/TM1637@0.0.0-alpha+sha.9486982048
	esp32async/ESPAsyncWebServer@^3.10.3
	gyverlibs/GTimer@^1.1.1
	miguelbalboa/MFRC522@^1.4.12
	jgromes/RadioLib@^7.7.1
extra_scripts = pre:scripts/convert_web_files.py
test_testing_command = 
	${platformio.packages_dir}/tool-openocd/bin/openocd
	-s
	${platformio.packages_dir}/tool-openocd
	-f
	openocd/scripts/board/st_nucleo_l1.cfg
	-c
	init
	-c
	arm semihosting enable
	-c
	reset run

[env:debug]
extends = env:esp32c3
platform = ${env:esp32c3.platform}
build_type = debug
build_flags = 
	${env:esp32c3.build_flags}
	-DDEBUG
debug_extra_cmds = 
	monitor arm semihosting enable
	monitor arm semihosting_fileio enable
;debug_tool = olimex-arm-usb-ocd-h
;upload_protocol = esp-builtin
debug_tool = esp-builtin
lib_deps = ${env:esp32c3.lib_deps}
board = ${env:esp32c3.board}
framework = ${env:esp32c3.framework}
monitor_speed = ${env:esp32c3.monitor_speed}
extra_scripts = ${env:esp32c3.extra_scripts}
board_build.f_cpu = ${env:esp32c3.board_build.f_cpu}
board_build.board_build.flash_mode = ${env:esp32c3.board_build.board_build.flash_mode}
board_build.f_flash = ${env:esp32c3.board_build.f_flash}
upload_speed = ${env:esp32c3.upload_speed}
monitor_dtr = ${env:esp32c3.monitor_dtr}
monitor_rts = ${env:esp32c3.monitor_rts}

[env:release]
extends = env:esp32c3
platform = ${env:esp32c3.platform}
build_type = release
build_flags = 
	${env:esp32c3.build_flags}
	-DNDEBUG
lib_deps = ${env:esp32c3.lib_deps}
board = ${env:esp32c3.board}
framework = ${env:esp32c3.framework}
monitor_speed = ${env:esp32c3.monitor_speed}
extra_scripts = ${env:esp32c3.extra_scripts}
board_build.f_cpu = ${env:esp32c3.board_build.f_cpu}
board_build.board_build.flash_mode = ${env:esp32c3.board_build.board_build.flash_mode}
board_build.f_flash = ${env:esp32c3.board_build.f_flash}
upload_speed = ${env:esp32c3.upload_speed}
monitor_dtr = ${env:esp32c3.monitor_dtr}
monitor_rts = ${env:esp32c3.monitor_rts}

[platformio]
description = Life Button for airsoft
